name: Coverage Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - id: last_coverage
      run: |
        last_cov=$(go tool cover -func=coverage.out | tail -1 | awk '{ print $3 }' | sed s/%//g)
        echo '::set-output name=LAST_COV::${last_cov}'

    - id: this_coverage
      run: |
        go test -coverprofile=coverage.out
        this_cov=$(go tool cover -func=coverage.out | tail -1 | awk '{ print $3 }' | sed s/%//g)
        echo '::set-output name=THIS_COV::${this_cov}'

    - name: Coverage comparison
      if: ${{ steps.last_coverage.outputs.LAST_COV > steps.this_coverage.outputs.THIS_COV }}
      run: |
        echo "Coverage has dropped from ${{ steps.last_coverage.outputs.LAST_COV }} to ${{ steps.this_coverage.outputs.THIS_COV }}"
        exit 1

    - name: Add coverage report
      uses: EndBug/add-and-commit@v7
      with:
        add: coverage.out
        message: "Update test coverage"

    - name: Convert to LCOV
      uses: jandelgado/gcov2lcov-action@v1.0.8
      with:
        infile: coverage.out
        outfile: lcov.info

    - name: Minimum coverage 100%
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      with:
        path: lcov.info
        min_coverage: 100
