name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage ./...

    - name: Cover
      run: go tool cover -func=coverage

    - name: gcov2lcov-action
      uses: jandelgado/gcov2lcov-action@v1.0.8
      with:
        infile: coverage
        outfile: lcov.info

    - name: Very Good Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
